platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def test_pods
pod 'FBSnapshotTestCase'
  pod 'Nimble', '~> 8.0.2'
  pod 'Quick', '~> 2.1.0'

end

target 'Pastel_Example' do
  pod 'Pastel', :path => '../'

  target 'Pastel_Tests' do
    inherit! :search_paths
    test_pods

  end
end
